filter:
    paths: 
        - 'app/code/local/Volcom/*'
        - 'app/code/local/Kering/*'
        - 'app/code/local/Electric/*'
        - 'app/code/local/OnePica/*'
        - 'shell/local/*'
    dependency_paths:
        - 'app/code/core/*'
        - 'app/code/community/*'
        - 'lib/*'
tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
checks:
    php:
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        unused_variables: true
        unused_properties: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true
        function_in_camel_caps: true
        encourage_single_quotes: true
        encourage_postdec_operator: true
        coding_standard: Magento
        avoid_multiple_statements_on_same_line: true
        remove_php_closing_tag: true
        one_class_per_file: true
        psr2_class_declaration: false
        no_underscore_prefix_in_properties: false
        no_underscore_prefix_in_methods: false
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: false
        braces:
            classes_functions:
                class: new-line
                function: new-line
                closure: end-of-line
            if:
                opening: end-of-line
            for:
                opening: end-of-line
            while:
                opening: end-of-line
            do_while:
                opening: end-of-line
            switch:
                opening: end-of-line
            try:
                opening: end-of-line
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower
build_failure_conditions:
    - 'elements.rating(<= D).new.exists'
    - 'issues.label("complexity").new.exists'
    - 'issues.label("unused-code").new.exists'
    - 'issues.label("coding-style").new.exists'
    - 'issues.label("security").new.exists'
    - 'issues.label("comprehensibility").new.exists'
    - 'issues.label("documentation").new.exists'
    - 'issues.label("naming").new.exists'
    - 'issues.label("bug").new.exists'
    - 'issues.label("performance").new.exists'
    - 'issues.label("deprecated-code").new.exists'
    - 'issues.label("configuration").new.exists'
    - 'issues.label("compatibility").new.exists'
    - 'issues.label("debugging-code").new.exists'
